# fly.toml app configuration file generated for restapi-server on 2023-10-11T20:00:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restapi-server"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
